### PR TITLE
release 0.1.1

### PR DESCRIPTION
**Pull request by michaelmcd18**

### CODE REVIEW

**Comment by michaelmcd18** [comment]
https://github.com/metrumresearchgroup/mrgmisc/compare/0.1.0...0.1.1

**Comment by kyleam** [comment]
Before making a release, can you silence the remaining notes in the checks?

**Comment by kyleam** [comment]
There's a mismatch between the version in the DESCRIPTION/title (0.1.1) and the one in the branch name:
image

**Comment by michaelmcd18** [comment]
@kyleam I realized after making the branch since there were no new features added it should go to 0.1.1 instead of 0.2.0

**Comment by kyleam** [comment]
> @kyleam I realized after making the branch since there were no new features added it should go to 0.1.1 instead of 0.2.0

I see.  I suggest renaming the branch to avoid the mismatch causing confusion when someone is looking back at the repo.

**Pull request closed without merging**
